name: Build Cryptomentor APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Patch Android (Gradle + Manifest)
        run: |
          sed -i 's/minSdkVersion.*/minSdkVersion 21/' android/app/build.gradle || true
          sed -i 's/shrinkResources true/shrinkResources false/g' android/app/build.gradle || true
          sed -i 's/minifyEnabled true/minifyEnabled false/g' android/app/build.gradle || true
          grep -q "multidex" android/app/build.gradle ||             sed -i '/dependencies {/a\    implementation "androidx.multidex:multidex:2.0.1"' android/app/build.gradle

          grep -q "android.permission.INTERNET" android/app/src/main/AndroidManifest.xml ||             sed -i '2i <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get

      - name: Build release APK
        run: flutter build apk --release -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk
          path: build/app/outputs/flutter-apk/*.apk
