name: Build APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"   # ổn định cho Gradle KTS
          channel: "stable"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Patch Android (Gradle + Manifest)
        shell: bash
        run: |
          set -e
          # Bảo đảm có android/ đầy đủ, build.gradle.kts, gradle-wrapper, manifest…
          test -d android || (echo "android/ missing" && exit 1)
          test -f android/app/build.gradle.kts || (echo "android/app/build.gradle.kts missing" && exit 1)

          # Bật multidex & tắt shrink/minify cho release
          sed -i 's/minSdk\s*=\s*[0-9]\+/minSdk = 21/' android/app/build.gradle.kts || true
          sed -i 's/multiDexEnabled\s*=\s*false/multiDexEnabled = true/' android/app/build.gradle.kts || true
          grep -q "multiDexEnabled" android/app/build.gradle.kts || \
            sed -i '/defaultConfig\s*{.*/a \ \ \ \ multiDexEnabled = true' android/app/build.gradle.kts

          # Tắt shrink/minify (nếu có)
          sed -i 's/minifyEnabled\s*=\s*true/minifyEnabled = false/g' android/app/build.gradle.kts || true
          sed -i 's/shrinkResources\s*=\s*true/shrinkResources = false/g' android/app/build.gradle.kts || true

          # Thêm INTERNET vào Manifest nếu thiếu
          if ! grep -q 'android.permission.INTERNET' android/app/src/main/AndroidManifest.xml; then
            sed -i 's|<application |<uses-permission android:name="android.permission.INTERNET" />\n<application |' android/app/src/main/AndroidManifest.xml
          fi

      - name: Flutter clean & get
        run: |
          flutter clean
          flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cryptomentor-APK
          path: build/app/outputs/flutter-apk/app-release.apk
