name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # TẠO BỘ KHUNG ANDROID/ (Gradle) VÌ REPO CHƯA CÓ
      # Lệnh này sẽ tạo đủ android/, ios/… và KHÔNG ghi đè code lib/pubspec sẵn có
      - name: Bootstrap Flutter app structure
        run: flutter create . --platforms=android -t app

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk
          path: build/app/outputs/flutter-apk/app-release.apk
