name: Android APK (FULL MAX)
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ensure platforms
        run: flutter create .

      - name: Pub get
        run: flutter pub get

      - name: Build release (verbose, no shrink)
        run: |
          set -euxo pipefail
          flutter build apk --release --no-shrink -v | tee release_build.log
          echo "== APK PATHS FOUND =="
          find build -type f -name "*.apk" || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: release_build.log
          path: release_build.log

      - name: Upload APK (catch-all)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/*-release.apk
            build/**/outputs/**/*.apk
          if-no-files-found: warn
