name: Android APK (Free APIs, Heavy Mock)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter create .
      - run: flutter pub get
      - name: Set packageId
        run: sed -i 's/applicationId ".*"/applicationId "com.cryptomentor.app"/' android/app/build.gradle || true
      - run: flutter build apk --release --no-shrink -v | tee release_build.log
      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/*.apk
