
name: build-apk

on:
  push:
    branches: [ "**" ]
    tags: [ "v*", "release-*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew || true

      - name: Build Debug APK
        run: |
          ./gradlew :app:assembleDebug
          ls -lah app/build/outputs/apk/debug || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
