name: Build Cryptomentor APK (Full UI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Extract full UI source
        run: unzip cryptomentor_src_fullui.zip -d ./src

      - name: Create Android/iOS folders
        run: cd src && flutter create .

      - name: Set app name to Cryptomentor
        run: |
          sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">Cryptomentor<\/string>/g' src/android/app/src/main/res/values/strings.xml || true
          sed -i 's/android:label="[^"]*"/android:label="@string\/app_name"/g' src/android/app/src/main/AndroidManifest.xml || true

      - name: Install dependencies
        run: cd src && flutter pub get

      - name: Build Debug APK
        run: cd src && flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: src/build/app/outputs/flutter-apk/app-debug.apk
