name: Build Android APK (Robust)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK 34 and Build Tools
        shell: bash
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter info
        run: |
          flutter --version
          flutter doctor -v

      - name: Get packages
        run: flutter pub get

      - name: Ensure gradlew executable (if native Android modules exist)
        run: |
          if [ -f "./android/gradlew" ]; then
            chmod +x ./android/gradlew || true
          fi
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew || true
          fi

      - name: Build APK (release with automatic debug fallback)
        id: build_apk
        shell: bash
        run: |
          set -e
          echo "Attempting release build..."
          if flutter build apk --release; then
            APK=build/app/outputs/flutter-apk/app-release.apk
            echo "variant=release" >> $GITHUB_OUTPUT
            echo "apk_path=$APK" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Release build failed. Falling back to debug build..."
          # In the same shell so Flutter stays in PATH
          flutter build apk --debug
          APK=build/app/outputs/flutter-apk/app-debug.apk
          echo "variant=debug" >> $GITHUB_OUTPUT
          echo "apk_path=$APK" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk-${{ steps.build_apk.outputs.variant }}
          path: ${{ steps.build_apk.outputs.apk_path }}
          if-no-files-found: error

      - name: Archive build logs
        if: always()
        run: |
          mkdir -p logs
          cp -r build/* logs/ || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: logs
