name: Build Android APK (Root Create)
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.22.0', channel: 'stable', cache: true }
      - uses: android-actions/setup-android@v3
        with: { api-level: 34, build-tools: 34.0.0 }
      - name: Create Flutter project at root
        run: |
          flutter create . --org com.cryptomentor.app -a kotlin
      - name: Inject project (from project/ folder)
        run: |
          rm -rf lib && mkdir -p lib
          cp -r project/lib/* lib/
          cp project/pubspec.yaml pubspec.yaml
          mkdir -p assets
          [ -d project/assets ] && cp -r project/assets/* assets/ || true
      - name: Ensure Android compile/min SDK
        run: |
          sed -i 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/' android/app/build.gradle || true
          sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' android/app/build.gradle || true
          echo "org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8" >> android/gradle.properties
      - run: flutter pub get
      - run: flutter build apk --release --verbose
      - uses: actions/upload-artifact@v4
        with: { name: Cryptomentor-APK, path: build/app/outputs/flutter-apk/app-release.apk }
