name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      # ⚠️ Nếu thiếu thư mục android/ thì bootstrap ngay
      - name: Bootstrap Android skeleton if missing
        run: |
          if [ ! -d "android" ]; then
            echo "android/ not found -> flutter create"
            # giữ nguyên packageName mặc định; có thể đổi sau trong android/app/build.gradle
            flutter create . --platforms=android -t app
          else
            echo "android/ found -> skip create"
          fi

      # Dọn cache Gradle phòng lỗi còn sót
      - name: Clean Gradle & Flutter
        run: |
          flutter clean
          rm -rf ~/.gradle/caches

      # Build debug để chắc chắn chạy được ngay (không cần keystore)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      # (Tùy chọn) Build release nếu muốn, sẽ fail nếu chưa có signingConfig
      - name: Try Build APK (release)
        continue-on-error: true
        run: flutter build apk --release

      - name: Upload release APK if exists
        if: ${{ success() || always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: ignore

      - name: Archive build logs
        if: always()
        run: |
          mkdir -p build-logs
          cp -r build/* build-logs/ || true
        shell: bash

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-logs
