name: Build Android APK (Self-healing)

on:
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
  ANDROID_HOME: ${{ github.workspace }}/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android commandline-tools & SDK (34)
        shell: bash
        run: |
          set -euxo pipefail
          SDK="$ANDROID_SDK_ROOT"
          mkdir -p "$SDK"
          cd "$SDK"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p cmdline-tools
          unzip -q cmdtools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          export PATH="$SDK/cmdline-tools/latest/bin:$SDK/platform-tools:$SDK/build-tools/34.0.0:$PATH"
          echo "$SDK/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$SDK/platform-tools" >> $GITHUB_PATH
          echo "$SDK/build-tools/34.0.0" >> $GITHUB_PATH
          "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --version
          set +o pipefail
          yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --licenses >/dev/null || true
          set -o pipefail
          "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --install             "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Detect Flutter app directory
        id: detect
        shell: bash
        run: |
          set -e
          if [ -f "pubspec.yaml" ]; then
            APP_DIR="."
          else
            APP_DIR=$(git ls-files | grep -E '^.*pubspec\.yaml$' | head -n1 | xargs -r dirname)
            if [ -z "$APP_DIR" ]; then
              echo "No pubspec.yaml found in repo" >&2
              exit 1
            fi
          fi
          echo "app_dir=$APP_DIR" >> $GITHUB_OUTPUT
          echo "Detected Flutter app dir: $APP_DIR"

      - name: Prepare project (auto-fix Gradle structure if needed)
        id: prep
        shell: bash
        run: |
          set -e
          cd "${{ steps.detect.outputs.app_dir }}"
          flutter pub get
          # If Android scaffolding missing -> create locally on runner only
          if [ ! -d "android" ] || [ ! -f "android/app/build.gradle" ] || [ ! -f "android/gradlew" ]; then
            echo "Android scaffolding missing -> flutter create . (runner-only, no commit)"
            flutter create .
          fi
          # Ensure wrapper is executable
          [ -f "android/gradlew" ] && chmod +x android/gradlew || true
          [ -f "gradlew" ] && chmod +x gradlew || true

      - name: Build APK (release with debug fallback; retry after auto-fix)
        id: build_apk
        shell: bash
        run: |
          set +e
          cd "${{ steps.detect.outputs.app_dir }}"
          echo "Attempting RELEASE build..."
          flutter build apk --release
          rc=$?
          if [ $rc -ne 0 ]; then
            echo "Release build failed ($rc). Trying DEBUG build..."
            flutter build apk --debug
            rc=$?
          fi
          if [ $rc -ne 0 ]; then
            echo "Build failed ($rc). Checking for 'unsupported Gradle project' and auto-fixing..."
            # Last resort: force-create android scaffolding then retry DEBUG build
            flutter create .
            [ -f "android/gradlew" ] && chmod +x android/gradlew || true
            flutter build apk --debug
            rc=$?
          fi
          if [ $rc -ne 0 ]; then
            echo "::error ::Flutter build failed with exit code $rc"
            exit $rc
          fi

      - name: Find built APK path
        id: find_apk
        shell: bash
        run: |
          set -e
          APP_DIR="${{ steps.detect.outputs.app_dir }}"
          APK=$(find "$APP_DIR/build/app/outputs" -type f -name "*.apk" 2>/dev/null | sort | tail -n1 || true)
          if [ -z "$APK" ]; then
            echo "::error ::No APK found under $APP_DIR/build/app/outputs. Check previous step logs for build errors."
            exit 1
          fi
          echo "apk_path=$APK" >> $GITHUB_OUTPUT
          echo "Found APK: $APK"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk
          path: ${{ steps.find_apk.outputs.apk_path }}
          if-no-files-found: error
