name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Bootstrap Android project if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android -t app
          fi
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle || true
          sed -i 's/applicationId "[^"]*"/applicationId "com.cryptomentor.app"/' android/app/build.gradle || true

      - name: Pub get
        run: flutter pub get

      - name: Clean and build (debug)
        run: |
          flutter clean
          rm -rf ~/.gradle/caches || true
          set -o pipefail
          flutter build apk --debug -v 2>&1 | tee debug_build.log

      - name: Build (release)
        run: |
          set -o pipefail
          flutter build apk --release -v 2>&1 | tee release_build.log

      - name: Upload APKs & Logs
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-artifacts
          path: |
            build/app/outputs/flutter-apk/*.apk
            debug_build.log
            release_build.log
          if-no-files-found: warn
