name: Build Android APK (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install Android SDK + sdkmanager in PATH
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK 34 and Build Tools
        shell: bash
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # Flutter toolchain
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get packages
        run: flutter pub get

      # Build APK (release); fall back to debug if release signing is not configured
      - name: Build release APK
        run: flutter build apk --release
      
      - name: Upload release APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: warn

      - name: Build debug APK (fallback)
        if: failure()
        run: |
          echo "Release build failed, building debug APK as fallback"
          flutter build apk --debug

      - name: Upload debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: ignore

      # Archive build logs
      - name: Archive build logs
        if: always()
        run: |
          mkdir -p logs
          cp -r build/* logs/ || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: logs
