name: Build Android APK (Patched)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      # Ensure Android SDK + build tools + licenses accepted
      - name: Set up Android SDK (API 34, Build-Tools 34.0.0)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          cmake: 'default'
          ndk: 'none'

      - name: Create base Flutter project
        run: flutter create cryptomentor --project-name cryptomentor --org com.cryptomentor.app -a kotlin

      - name: Inject project files
        run: |
          cp pubspec.yaml cryptomentor/pubspec.yaml
          rm -rf cryptomentor/lib
          mkdir -p cryptomentor/lib
          cp -r lib/* cryptomentor/lib/
          mkdir -p cryptomentor/assets
          cp -r assets/* cryptomentor/assets/ || true

      # Defensive bumps in case template defaults differ
      - name: Ensure Android compile/min SDK
        run: |
          sed -i 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/' cryptomentor/android/app/build.gradle || true
          sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' cryptomentor/android/app/build.gradle || true

      - name: Flutter pub get
        working-directory: cryptomentor
        run: flutter pub get

      - name: Flutter doctor (diagnostics)
        working-directory: cryptomentor
        run: flutter doctor -v

      - name: Build APK (release)
        working-directory: cryptomentor
        run: flutter build apk --release --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cryptomentor-APK
          path: cryptomentor/build/app/outputs/flutter-apk/app-release.apk
