
name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with: { distribution: 'temurin', java-version: '17' }
    - uses: subosito/flutter-action@v2
      with: { channel: 'stable', cache: true }
    - name: Bootstrap Android project if missing
      run: |
        if [ ! -d "android" ]; then flutter create . --platforms=android -t app; fi
        sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle || true
        sed -i 's/applicationId "[^"]*"/applicationId "com.cryptomentor.app"/' android/app/build.gradle || true
    - run: flutter pub get
    - run: flutter build apk --debug -v
    - run: flutter build apk --release -v
    - uses: actions/upload-artifact@v4
      with: { name: cryptomentor-apk, path: build/app/outputs/flutter-apk/*.apk, if-no-files-found: error }
