name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # Tạo project Flutter trong thư mục con có tên hợp lệ (không dính dấu '-')
      - name: Bootstrap Flutter app in subdir
        run: |
          rm -rf app
          flutter create app --platforms=android -t app --project-name cryptomentorapp
          # chép source của anh vào app/
          cp -r lib app/
          cp pubspec.yaml app/

      - name: Flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build APK (release)
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cryptomentor-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
